name: Build and Deploy Docs
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sphinxdoc/sphinx:5.3.0
      volumes:
        - docs:/docs
    steps:
      - name: debug
        run: ls docs
      - name: Build Site
        run: make -C docs html
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/html'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2